### ISSUE TITLE
Fatal error: Cannot unset $this in admin/includes/classes/upload.php

### ISSUE THREAD

**Issue by timint** [loadedcommerce/loaded75ce#1]
Fresh install. Latest version from Softaculous.

**Fatal error:** Cannot unset $this in admin/includes/classes/upload.php

```
        } else {
// self destruct
         // $this = null;
         unset($this);
// JACK COMMENTED THIS OUT TO MAKE THE ADMIN WORK FOR PHP 5.0.3 ,
// Tom added new unset for php5

          return false;
        }
```

Edit: Wrong repository. Softaculous was on 6.5.3.3. I'm not entitled to delete my own issue ticket.

**Comment by saliozzia** [comment]
its ok, thanks for posting this, 

we are moving to gitlab any in our next release, Here is the new repo and issue list:
https://gitlab.com/Loaded-commerce/Loaded6/issues

**Comment by saliozzia** [comment]
Wrong Edition
